//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netOpen {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class OptData : global::System.Configuration.ApplicationSettingsBase {
        
        private static OptData defaultInstance = ((OptData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OptData())));
        
        public static OptData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowHidenRes {
            get {
                return ((bool)(this["ShowHidenRes"]));
            }
            set {
                this["ShowHidenRes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int PingBufferLen {
            get {
                return ((int)(this["PingBufferLen"]));
            }
            set {
                this["PingBufferLen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RememberPClist {
            get {
                return ((bool)(this["RememberPClist"]));
            }
            set {
                this["RememberPClist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int PingWaitTime {
            get {
                return ((int)(this["PingWaitTime"]));
            }
            set {
                this["PingWaitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PingPacketFragment {
            get {
                return ((bool)(this["PingPacketFragment"]));
            }
            set {
                this["PingPacketFragment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("254")]
        public byte ScanThreadAmount {
            get {
                return ((byte)(this["ScanThreadAmount"]));
            }
            set {
                this["ScanThreadAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.ListViewItem change {
            get {
                return ((global::System.Windows.Forms.ListViewItem)(this["change"]));
            }
            set {
                this["change"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Add {
            get {
                return ((bool)(this["Add"]));
            }
            set {
                this["Add"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.Form OptForm {
            get {
                return ((global::System.Windows.Forms.Form)(this["OptForm"]));
            }
            set {
                this["OptForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.Form MainForm {
            get {
                return ((global::System.Windows.Forms.Form)(this["MainForm"]));
            }
            set {
                this["MainForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.ListView diapListH {
            get {
                return ((global::System.Windows.Forms.ListView)(this["diapListH"]));
            }
            set {
                this["diapListH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DiapCount {
            get {
                return ((int)(this["DiapCount"]));
            }
            set {
                this["DiapCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StatusBarVisible {
            get {
                return ((bool)(this["StatusBarVisible"]));
            }
            set {
                this["StatusBarVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.ToolStripMenuItem ZaklData {
            get {
                return ((global::System.Windows.Forms.ToolStripMenuItem)(this["ZaklData"]));
            }
            set {
                this["ZaklData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.ListViewItem CurActiveItem {
            get {
                return ((global::System.Windows.Forms.ListViewItem)(this["CurActiveItem"]));
            }
            set {
                this["CurActiveItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.NotifyIcon NotifyMe {
            get {
                return ((global::System.Windows.Forms.NotifyIcon)(this["NotifyMe"]));
            }
            set {
                this["NotifyMe"] = value;
            }
        }
    }
}
